version: "3.8"

services:
  backend:
    image: new-backend
    ports:
      - 8080:8080
    environment:
      REQUEST_ORIGIN: http://10.0.0.108
      REDIS_HOST: redis
      POSTGRES_PORT: 5432
      POSTGRES_HOST: Postgres
      POSTGRES_USER: barny
      POSTGRES_PASSWORD: Elon-it/4u
      POSTGRES_DATABASE: postgres

  frontend:
    image: new-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://10.0.0.108/api/
    depends_on:
      - backend
  redis:
    image: redis
    ports:
      - 6379:6379
  Postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: barny
      POSTGRES_PASSWORD: Elon-it/4u
      POSTGRES_DB: postgres
    volumes:
      - ./test:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend