version: '3.8'

services:
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://192.168.1.32:5000
      - REDIS_HOST=redis

  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://192.168.1.32:8080
    depends_on:
      - backend
  redis:
    image: redis
    ports:
      - 6379:6379